module-3/09-Data-Validation-and-View-Models/lecture-final/CitySearch/Forms.Web/Models/City.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Forms.Web.Models
{
    public class City
    {
        /*** TODO 03: Add model validations
         * Name: Required
         * CountryCode: Display Name = Country Code, Required, String Length = 3
         * District: Required
         * Population: Required, Range 1-99,999,999
         ***/
        public int CityId { get;  set; }

        [Required(ErrorMessage = "*")]
        public string Name { get;  set; }

        [Required]
        [StringLength(3, MinimumLength = 3, ErrorMessage = "Country Code must be exactly 3  characters.")]
        [Display(Name="Country Code", Prompt="e.g., \"USA\"")]
        public string CountryCode { get;  set; }

        [Required]
        public string District { get; set; }

        [Range(1, 99999999)]
        public int Population { get;  set; }
    }
}

module-3/09-Data-Validation-and-View-Models/lecture-final/CitySearch/Forms.Web/Models/CitySearchVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Forms.Web.Models
{
    public class CitySearchVM
    {
        public string CountryCode { get; set; }
        public string District { get; set; }
        public IList<City> Cities { get; set; }

        // Generate Select List from the DAO
        // Add a place to store a list of countries to the view-model
        public SelectList CountryList { get; set; }

    }
}

module-3/09-Data-Validation-and-View-Models/lecture-final/CitySearch/Forms.Web/Models/ErrorViewModel.cs
using System;

namespace Forms.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

module-3/09-Data-Validation-and-View-Models/lecture-final/CitySearch/Forms.Web/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Forms.Web.DAL;
using Forms.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Forms.Web.Controllers
{
    public class CityController : Controller
    {
        private ICityDAO cityDAO;

        public CityController(ICityDAO cityDAO)
        {
            this.cityDAO = cityDAO;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Search(CitySearchVM vm)
        {
            if (vm.CountryCode != null)
            {
                // Use the dao to get the cities that match the search
                vm.Cities = cityDAO.GetCities(vm.CountryCode, vm.District);
            }

            // Call the GetCountries private method, which Populates the country list on the view model
            vm.CountryList = GetCountries();

            // Pass the results into the SearchResults view for display
            return View(vm);
        }

        // Create a method which creates a list of SelectListItems for a dropdown
        private SelectList GetCountries()
        {
            // Populate the country search list
            IList<Country> countries = cityDAO.GetCountries();
            SelectList countryList = new SelectList(countries, "Code", "Name");
            return countryList;
        }

        // Create an Action to handle the Add City, GET
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(City city)
        {
            // I might put some validation here, but I am lazy

            // TODO 05: Check model state before updating. If there are errors, return the form to the user.
            if (!ModelState.IsValid)
            {
                return View(city);
            }

            // Use the dao to add the city
            int newCityId = cityDAO.AddCity(city);

            // TODO 02a: Store a message in TempData to be shown to the user
            TempData["message"] = $"The city '{city.Name}' was added. The new city ID is {newCityId}.";

            // Redirect to a confirmation page
            //return RedirectToAction("AddConfirmation", new { id = newCityId });
            // TODO 01: Redirect from add to search, passing Country and District in
            CitySearchVM vm = new CitySearchVM()
            {
                CountryCode = city.CountryCode,
                District = city.District
            };
            return RedirectToAction("Search", vm);
        }

        [HttpGet]
        public IActionResult AddConfirmation(int id)
        {
            City city = cityDAO.GetCityById(id);
            return View(city);
        }

        // TODO BONUS 01: Create a City Detail page
        // TODO BONUS 01a: Create a Detail (GET) method to handle the request and show the form
        // TODO BONUS 01b: Create the City Detail form to show information from the user. Include links to UPD and DEL.

        // TODO BONUS 02: Implement the PRG pattern to DELETE a city
        // TODO BONUS 02a: Create a Delete (GET) method to handle the request and show the form
        // TODO BONUS 02b: Create the Delete City form to show information to the user and confirm
        // TODO BONUS 02c: Create a Delete (POST) method to call the dao to delete a city
        // TODO BONUS 02d: Create the confirmation (Get) method call the view to confirm
        // TODO BONUS 02e: Create the Confirmation page to show the successful Delete

        // TODO BONUS 03: Implement flow to UPDATE a city
        // TODO BONUS 03a: Create an Update (GET) method to handle the request and show the form
        // TODO BONUS 03b: Create the Update City form to show / get information to the user
        // TODO BONUS 03c: Create an Update (POST) method to call the dao to update a city
        // TODO BONUS 03d: Redirect to the Update (GET) page
    }
}

module-3/09-Data-Validation-and-View-Models/lecture-final/CitySearch/Forms.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Forms.Web.Models;
using Forms.Web.DAL;

namespace Forms.Web.Controllers
{
    public class HomeController : Controller
    {        
        /// <summary>
        /// Represents an index action.
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }   
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


    }
}

module-3/09-Data-Validation-and-View-Models/lecture-final/CitySearch/Forms.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Forms.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Forms.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="City" asp-action="Search">Search</a></li>
                    <li><a asp-area="" asp-controller="City" asp-action="Add">Add City</a></li>
                </ul>
            </div>
        </div>
    </nav>

    @{
        // TODO 02: Add a spot in the layout for a message to the user
    }
    @if (TempData["message"] != null)
    {
    <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>@TempData["message"]</strong>
    </div>
    }

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Forms.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>